<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class MaterialOrder extends Model
{
    const STATUS_NOT_STARTED = 0;
    const STATUS_IN_PROCESS = 1;
    const STATUS_DONE = 2;
    const STATUS_CANCELED = 3;
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function(MaterialOrder $materialOrder) {
            $materialOrder->uuid = Str::uuid();
        });
    }

    protected $table = 'm_orders';
    protected $fillable = ['user_id', 'city_id', 'material_id', 'count',
        'delivery_deadline', 'address', 'lat', 'long', 'price', 'description'];
    protected $appends = ['status_name'];

    protected $hidden = ['updated_at'];

    public function getStatusNameAttribute() {
        return trans("order_statuses.material.$this->status");
    }

    public function responses() {
        return $this->hasMany(MaterialOrderResponse::class, 'order_id');
    }

    public function city() {
        return $this->belongsTo(City::class);
    }

    public function material() {
        return $this->belongsTo(Material::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function executor() {
        return $this->belongsTo(User::class, 'executor_id');
    }

    public function executorMaterial() {
        return $this->belongsTo(UserMaterials::class, 'executor_material_id');
            //->materialJoined();
    }

}
