<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class MaterialOrder extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function(MaterialOrder $materialOrder) {
            $materialOrder->uuid = Str::uuid();
        });
    }

    protected $table = 'm_orders';
    protected $fillable = ['user_id', 'city_id', 'material_id', 'count',
        'delivery_deadline', 'address', 'lat', 'long', 'price', 'description'];

    protected $hidden = ['created_at', 'updated_at'];

}
